from telegram.ext import ConversationHandler
(
    NOTE_TEXT, REMIND_TEXT, 
    VIEW_NOTES, EDIT_NOTE_TITLE, EDIT_NOTE_DETAIL, DELETE_NOTE,
    VIEW_REMINDERS, EDIT_REMINDER_TITLE, EDIT_REMINDER_DETAIL, EDIT_REMINDER_TIME, DELETE_REMINDER,
    PROMPTING,
    ) = range(12)

END = ConversationHandler.END